baseURL = "https://ReginRavi.github.io/personal-knowledge-base/"
languageCode = "en-us"
title = "My Knowledge Base"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowToc = true
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Knowledge Base"
  Content = "Personal notes and deep dives into Kubernetes, Terraform, and AWS"

[[menu.main]]
  name = "Kubernetes"
  url = "/kubernetes/"
  weight = 1

[[menu.main]]
  name = "Terraform"
  url = "/terraform/"
  weight = 2

[[menu.main]]
  name = "AWS"
  url = "/aws/"
  weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]
